apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-connect.name" . }}-hook
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.hook.argocd.enabled }}
    {{- include "kafka-connect-hook.argocd-syncwave" . | nindent 4 }}
    argocd.argoproj.io/hook: PostSync
    {{- else }}
    "helm.sh/hook": post-install
    {{- end }}
